# TCL File Generated by Component Editor 24.3
# Thu Nov 14 03:45:36 PST 2024
# DO NOT MODIFY


# 
# irq_bypass "irq_bypass" v1.0
#  2024.11.14.03:45:36
# 
# 

# 
# request TCL package from ACDS 24.3
# 
package require -exact qsys 24.3


# 
# module irq_bypass
# 
set_module_property DESCRIPTION ""
set_module_property NAME irq_bypass
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property BSP_CPU false
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME irq_bypass
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false
set_module_property LOAD_ELABORATION_LIMIT 0
set_module_property PRE_COMP_MODULE_ENABLED false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL irq_bypass
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file irq_bypass.sv SYSTEM_VERILOG PATH ../src/custom_rtl/irq_bypass/irq_bypass.sv TOP_LEVEL_FILE

add_fileset SIM_VERILOG SIM_VERILOG "" ""
set_fileset_property SIM_VERILOG TOP_LEVEL irq_bypass
set_fileset_property SIM_VERILOG ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property SIM_VERILOG ENABLE_FILE_OVERWRITE_MODE true
add_fileset_file irq_bypass.sv SYSTEM_VERILOG PATH ../src/custom_rtl/irq_bypass/irq_bypass.sv


# 
# parameters
# 


# 
# display items
# 


# 
# connection point interrupt_sender
# 
add_interface interrupt_sender interrupt end
set_interface_property interrupt_sender bridgedReceiverOffset ""
set_interface_property interrupt_sender bridgesToReceiver ""
set_interface_property interrupt_sender ENABLED true
set_interface_property interrupt_sender EXPORT_OF ""
set_interface_property interrupt_sender PORT_NAME_MAP ""
set_interface_property interrupt_sender CMSIS_SVD_VARIABLES ""
set_interface_property interrupt_sender SVD_ADDRESS_GROUP ""
set_interface_property interrupt_sender IPXACT_REGISTER_MAP_VARIABLES ""
set_interface_property interrupt_sender SV_INTERFACE_TYPE ""
set_interface_property interrupt_sender SV_INTERFACE_MODPORT_TYPE ""

add_interface_port interrupt_sender interrupt_sender_irq irq Output 1


# 
# connection point interrupt_receiver
# 
add_interface interrupt_receiver interrupt start
set_interface_property interrupt_receiver irqScheme INDIVIDUAL_REQUESTS
set_interface_property interrupt_receiver ENABLED true
set_interface_property interrupt_receiver EXPORT_OF ""
set_interface_property interrupt_receiver PORT_NAME_MAP ""
set_interface_property interrupt_receiver CMSIS_SVD_VARIABLES ""
set_interface_property interrupt_receiver SVD_ADDRESS_GROUP ""
set_interface_property interrupt_receiver IPXACT_REGISTER_MAP_VARIABLES ""
set_interface_property interrupt_receiver SV_INTERFACE_TYPE ""
set_interface_property interrupt_receiver SV_INTERFACE_MODPORT_TYPE ""

add_interface_port interrupt_receiver interrupt_receiver_irq irq Input 1

