
# ######################################################################## 
# Copyright (C) 2025 Altera Corporation.
# SPDX-License-Identifier: MIT
# ######################################################################## 
# -------------------------------------------------------------------------- #
set_time_format -unit ns -decimal_places 3

set qsfp_csr_clk soc_inst|iopll_0|iopll_csr_clk
set zl_clk l4_sp_clk_src
set dma_clk_grp soc_inst|iopll_0|iopll_dma_clk
set hssi_clk_p0_grp gen_mulit_inst[0].hssi_ss_top|u0|intel_eth_gts_0|sip_inst|ptp_tx_clkout
set hssi_clk_p1_grp gen_mulit_inst[1].hssi_ss_top|u0|intel_eth_gts_0|sip_inst|ptp_tx_clkout
set csr_clk_grp soc_inst|iopll_0|iopll_csr_clk

set_clock_groups -asynchronous \
   -group [get_clocks $dma_clk_grp] \
   -group [get_clocks $hssi_clk_p0_grp]
	
set_clock_groups -asynchronous \
   -group [get_clocks $dma_clk_grp] \
   -group [get_clocks $hssi_clk_p1_grp]
	
set_clock_groups -asynchronous \
   -group [get_clocks $csr_clk_grp] \
   -group [get_clocks $hssi_clk_p0_grp]
	
set_clock_groups -asynchronous \
   -group [get_clocks $csr_clk_grp] \
   -group [get_clocks $hssi_clk_p1_grp]
	

set_input_delay   -source_latency_included 1 -clock $qsfp_csr_clk  [get_ports qsfp_i2c_sda]
set_output_delay  -source_latency_included 1 -clock $qsfp_csr_clk [get_ports qsfp_i2c_scl]
set_output_delay  -source_latency_included 1 -clock $qsfp_csr_clk  [get_ports {qsfpa_modeseln[*]}]
set_output_delay  -source_latency_included 1 -clock $qsfp_csr_clk  [get_ports {qsfpa_lpmode[*]}]
set_output_delay  -source_latency_included 1 -clock $qsfp_csr_clk  [get_ports {qsfpa_resetn[*]}]
set_output_delay  -source_latency_included 1 -clock $qsfp_csr_clk [get_ports {o_ptp_pps}]
set_input_delay   -source_latency_included 1 -clock $zl_clk [get_ports zl_i2c_sda]
set_output_delay  -source_latency_included 1 -clock $zl_clk  [get_ports zl_i2c_scl]

set_false_path -from [get_ports {qsfp_i2c_scl}] -to *
set_false_path -from * -to [get_ports {qsfp_i2c_scl}]
set_false_path -from [get_ports {zl_i2c_scl}] -to *
set_false_path -from * -to [get_ports {zl_i2c_scl}]
set_false_path -from [get_ports {qsfp_i2c_sda}] -to *
set_false_path -from * -to [get_ports {qsfp_i2c_sda}]
set_false_path -from [get_ports {zl_i2c_sda}] -to *
set_false_path -from * -to [get_ports {zl_i2c_sda}]
set_false_path -from [get_ports {qsfpa_modprsln[*]}] -to *
set_false_path -from [get_ports {intn_qsfp}] -to *
set_false_path -from * -to [get_ports {qsfpa_modeseln[*]}]
set_false_path -from * -to [get_ports {qsfpa_lpmode[*]}]
set_false_path -from * -to [get_ports {qsfpa_resetn[*]}]
set_false_path -from * -to [get_ports {o_ptp_pps}]
set_false_path -from * -to [get_ports {o_clk_rec_div_66}]
set_false_path -from * -to [get_ports {o_clk_rec_div_66(n)}]

set_false_path -from [get_keepers -no_duplicates {soc_inst|iopll_0|iopll|tennm_ph2_iopll~pll_ctrl_reg}] -to [get_keepers -no_duplicates {sync_iopll_lock_161_*|dreg[*]}]
set_false_path -from [get_keepers -no_duplicates {gen_mulit_inst[*].hssi_ss_top|u0|intel_eth_gts_0|hip_inst|n_channel_superset_wrapper_inst|n_channel_superset|hal_top_wrapper_inst|hal_top_ip|one_lane_inst_0|one_lane_hal_top_p0|gen_non_usb_mode.pldif_hal_top_inst|pldif_hal_top|pldif_hal_coreip_inst|gen_sm_ch4_pldif_inst.sm_block.ch4_pldif_inst|x_std_sm_hssi_pld_chnl_dp_0~pldif_reset_reg}] -to [get_keepers -no_duplicates {sts_tx_pll_locked[*].tx_pll_locked|dreg[*]}]
set_false_path -from [get_keepers -no_duplicates {gen_mulit_inst[*].hssi_ss_top|u0|intel_eth_gts_0|sip_inst|o_rx_pcs_ready}] -to [get_keepers -no_duplicates {sts_rx_pcs_ready[*].rx_pcs_ready|dreg[*]}]
set_false_path -from [get_keepers -no_duplicates {gen_mulit_inst[*].hssi_ss_top|u0|intel_eth_gts_0|sip_inst|o_tx_lanes_stable}] -to [get_keepers -no_duplicates {sts_tx_lanes_stable[*].tx_lanes_stable|dreg[*]}]
set_false_path -from [get_keepers -no_duplicates {soc_inst|iopll_0|iopll|tennm_ph2_iopll~pll_ctrl_reg}] -to [get_keepers -no_duplicates {sync_iopll_lock_125M|dreg[*]}]
set_false_path -from [get_keepers -no_duplicates {soc_inst|subsys_msgdma_p1_eth_ch0|rst_controller*|alt_rst_sync_uq1|altera_reset_synchronizer_int_chain_out}] -to [get_keepers -no_duplicates {soc_inst|subsys_msgdma_p1_eth_ch0|rx_dma_fifo_0|rx_dma_fifo_0|ts_fifo_rst}]
set_false_path -from [get_keepers -no_duplicates {soc_inst|subsys_msgdma_p1_eth_ch0|rst_controller*|alt_rst_sync_uq1|altera_reset_synchronizer_int_chain_out}] -to [get_keepers -no_duplicates {soc_inst|subsys_msgdma_p1_eth_ch0|rx_dma_fifo_0|rx_dma_fifo_0|to_cntr[*]}]
set_false_path -from [get_keepers -no_duplicates {soc_inst|subsys_msgdma_p1_eth_ch0|rst_controller*|alt_rst_sync_uq1|altera_reset_synchronizer_int_chain_out}] -to [get_keepers -no_duplicates {soc_inst|subsys_msgdma_p1_eth_ch0|rx_dma_fifo_0|rx_dma_fifo_0|cdc_packet_fifo|*}]
set_false_path -from [get_keepers -no_duplicates {soc_inst|subsys_msgdma_p0_eth_ch0|rst_controller*|alt_rst_sync_uq1|altera_reset_synchronizer_int_chain_out}] -to [get_keepers -no_duplicates {soc_inst|subsys_msgdma_p0_eth_ch0|rx_dma_fifo_0|rx_dma_fifo_0|ts_fifo_rst}]
set_false_path -from [get_keepers -no_duplicates {soc_inst|subsys_msgdma_p0_eth_ch0|rst_controller*|alt_rst_sync_uq1|altera_reset_synchronizer_int_chain_out}] -to [get_keepers -no_duplicates {soc_inst|subsys_msgdma_p0_eth_ch0|rx_dma_fifo_0|rx_dma_fifo_0|to_cntr[*]}]
set_false_path -from [get_keepers -no_duplicates {soc_inst|subsys_msgdma_p0_eth_ch0|rst_controller*|alt_rst_sync_uq1|altera_reset_synchronizer_int_chain_out}] -to [get_keepers -no_duplicates {soc_inst|subsys_msgdma_p0_eth_ch0|rx_dma_fifo_0|rx_dma_fifo_0|cdc_packet_fifo|*}]
set_false_path -from [get_keepers -no_duplicates {soc_inst|subsys_msgdma_p*_eth_ch*|rst_controller*|alt_rst_sync_uq1|altera_reset_synchronizer_int_chain_out}] -to [get_keepers -no_duplicates {soc_inst|subsys_msgdma_p*_eth_ch*|tx_dma_fifo_0_ch2|tx_dma_fifo_0|fingerprint[*]}]
set_false_path -from [get_keepers -no_duplicates {packet_switch_subsys|gen_tcam_inst[*].inst_tcam|mem_ss_cam_0|tcam_inst|ms_tcam_regs_inst|mgmt_ctrl_reg.op_type[*]}] -to [get_keepers -no_duplicates {packet_switch_subsys|gen_tcam_inst[*].inst_tcam|mem_ss_cam_0|tcam_inst|sync1_mgmt_req_type[*]}]
set_false_path -from [get_keepers -no_duplicates {packet_switch_subsys|gen_tcam_inst[*].inst_tcam|mem_ss_cam_0|tcam_inst|entry_vld}] -to [get_keepers -no_duplicates {packet_switch_subsys|gen_tcam_inst[*].inst_tcam|mem_ss_cam_0|tcam_inst|sync_entry_vld}]
set_false_path -from [get_keepers -no_duplicates {packet_switch_subsys|gen_tcam_inst[*].inst_tcam|mem_ss_cam_0|tcam_inst|ms_tcam_regs_inst|mgmt_ctrl_reg.op_type[*]}] -to [get_keepers -no_duplicates {packet_switch_subsys|gen_tcam_inst[*].inst_tcam|mem_ss_cam_0|tcam_inst|sync1_mgmt_req_type[*]}]
set_false_path -from [get_keepers -no_duplicates {packet_switch_subsys|gen_tcam_inst[*].inst_tcam|mem_ss_cam_0|tcam_inst|ms_tcam_reset_manager_inst|ms_tcam_reset_sequencer_inst|int_warm_rst_n*}] -to [get_keepers -no_duplicates {packet_switch_subsys|gen_tcam_inst[*].inst_tcam|mem_ss_cam_0|tcam_inst|ms_tcam_reset_manager_inst|int_warm_rst_n_d1}]
set_false_path -from [get_keepers -no_duplicates {packet_switch_subsys|gen_tcam_inst[*].inst_tcam|mem_ss_cam_0|tcam_inst|ms_tcam_regs_inst|mgmt_ctrl_reg.op_type[*]*}] -to [get_keepers -no_duplicates {packet_switch_subsys|gen_tcam_inst[*].inst_tcam|mem_ss_cam_0|tcam_inst|sync1_mgmt_req_type[*]}]
set_false_path -from [get_keepers -no_duplicates {packet_switch_subsys|gen_tcam_inst[*].inst_tcam|mem_ss_cam_0|tcam_inst|req_fifo_full_clk_extender|data_out}] -to [get_keepers -no_duplicates {packet_switch_subsys|gen_tcam_inst[*].inst_tcam|mem_ss_cam_0|tcam_inst|sync1_err_req_fifo_full}]
set_false_path -from [get_keepers -no_duplicates {packet_switch_subsys|gen_tcam_inst[*].inst_tcam|mem_ss_cam_0|tcam_inst|err_mgmt_req_valid}] -to [get_keepers -no_duplicates {packet_switch_subsys|gen_tcam_inst[*].inst_tcam|mem_ss_cam_0|tcam_inst|sync1_err_mgmt_req_valid}]
set_false_path -from [get_keepers -no_duplicates {packet_switch_subsys|gen_tcam_inst[*].inst_tcam|mem_ss_cam_0|tcam_inst|init_done}] -to [get_keepers -no_duplicates {packet_switch_subsys|gen_tcam_inst[*].inst_tcam|mem_ss_cam_0|tcam_inst|sync1_init_done}]
set_false_path -from [get_keepers -no_duplicates {packet_switch_subsys|gen_tcam_inst[*].inst_tcam|mem_ss_cam_0|tcam_inst|mgmt_resp_success}] -to [get_keepers -no_duplicates {packet_switch_subsys|gen_tcam_inst[*].inst_tcam|mem_ss_cam_0|tcam_inst|sync1_mgmt_resp_success}]
set_false_path -from [get_keepers -no_duplicates {packet_switch_subsys|gen_tcam_inst[*].inst_tcam|mem_ss_cam_0|tcam_inst|tg_sync_resp_valid|reg_in*}] -to [get_keepers -no_duplicates {packet_switch_subsys|gen_tcam_inst[*].inst_tcam|mem_ss_cam_0|tcam_inst|tg_sync_resp_valid|reg_out[*]}]
set_false_path -from [get_keepers -no_duplicates {soc_inst|subsys_msgdma_p*_eth_ch*|rst_controller|alt_rst_sync_uq1|altera_reset_synchronizer_int_chain_out}] -to [get_keepers -no_duplicates {soc_inst|subsys_msgdma_p*_eth_ch*|rx_dma_fifo_0_ch2|rx_dma_fifo_0|ts_fifo_rst}]
set_false_path -from [get_keepers -no_duplicates {soc_inst|subsys_msgdma_p*_eth_ch*|rst_controller|alt_rst_sync_uq1|altera_reset_synchronizer_int_chain_out}] -to [get_keepers -no_duplicates {soc_inst|subsys_msgdma_p*_eth_ch*|rx_dma_fifo_0_ch2|rx_dma_fifo_0|to_cntr[*]}]
set_false_path -from [get_keepers -no_duplicates {packet_switch_subsys|gen_tcam_inst[*].inst_tcam|mem_ss_cam_0|tcam_inst|ms_tcam_reset_manager_inst|ms_tcam_reset_sequencer_inst|int_cold_rst_n}] -to [get_keepers -no_duplicates {packet_switch_subsys|gen_tcam_inst[*].inst_tcam|mem_ss_cam_0|tcam_inst|mgmt_req|dcfifo_component|auto_generated|*aclr*}]
set_false_path -from [get_keepers -no_duplicates {packet_switch_subsys|packet_switch_top|gen_rst_sync[*].*x_rst_sync|syn_rst}] -to [get_keepers -no_duplicates {packet_switch_subsys|packet_switch_top|packet_switch_axi_lt_avmm_inst|gen_axi_lt_to_avmm[*].axi_lt_to_avmm_*x|bresp_cdc_fifo|auto_generated|rdaclr*}]
set_false_path -from [get_keepers -no_duplicates {packet_switch_subsys|gen_tcam_inst[*].inst_tcam|mem_ss_cam_0|tcam_inst|ms_tcam_reset_manager_inst|int_warm_rst_n}] -to [get_keepers -no_duplicates {packet_switch_subsys|gen_tcam_inst[*].inst_tcam|mem_ss_cam_0|tcam_inst|mgmt_resp|dcfifo_component|auto_generated|rdaclr*}]
set_false_path -from [get_keepers -no_duplicates {master_tod_rst_sync|resync_chains[0].synchronizer_nocut|dreg_R}] -to [get_keepers -no_duplicates {master_tod|MTOD_GEN_PPS_ADV_MODE.master_tod|eth_1588_tod_0|genblk3.u_pulse_per_second_w|GTS_ADV_MODE_PPS.u_pulse_per_second_gts_adv|u_rst_sync_sampling_clk|nocut_sync[0].std_sync_no_cut|dreg[*]}]; 
set_false_path -from [get_keepers -no_duplicates {inst_srd_rst_ctrl|o_user_tx_rst_n_100_*d[*]*}] -to [get_keepers -no_duplicates {soc_inst|subsys_msgdma_p*_eth_ch*|ts_chs_compl_0|ts_chs_compl_0|ts_ch_resp[*].ts_fifo|dcfifo_component|auto_generated|wraclr|*}]
set_false_path -from [get_keepers -no_duplicates {rd1|cntr[*]}] -to [get_keepers -no_duplicates {sync_ninit_done|*}]
set_false_path -from [get_keepers -no_duplicates {sync_iopll_lock_100M*|dreg[*]}] -to [get_keepers -no_duplicates {soc_inst|subsys_msgdma_p*_eth_ch*|*x_dma_fifo*|*x_dma_fifo*|cdc_packet_fifo|*}]
set_false_path -from [get_keepers -no_duplicates {inst_srd_rst_ctrl|o_user_*x_rst_n_100_*d[*]}] -to [get_keepers -no_duplicates {soc_inst|subsys_msgdma_p*_eth_ch*|ts_chs_compl_0|ts_chs_compl_0|*}]
set_false_path -from [get_keepers -no_duplicates {inst_srd_rst_ctrl|o_user_*x_rst_n_100_*d[*]}] -to [get_keepers -no_duplicates {soc_inst|subsys_msgdma_p*_eth_ch*|*x_dma_fifo_*|*x_dma_fifo_0|*}]
set_false_path -from [get_keepers -no_duplicates {sync_iopll_lock_100M|dreg[*]}] -to [get_keepers -no_duplicates {soc_inst|subsys_msgdma_p*_eth_ch*|ts_chs_compl_0|ts_chs_compl_0|*}]
set_false_path -from [get_keepers -no_duplicates {sync_iopll_lock_100M|dreg[*]}] -to [get_keepers -no_duplicates {soc_inst|subsys_msgdma_p*_eth_ch*|ts_chs_compl_0|ts_chs_compl_0|ts_p_data*}]
set_false_path -from [get_keepers -no_duplicates {inst_srd_rst_ctrl|eth_reset_sync[*].eth_user_*x_rstn_sync_100M|dreg[*]}] -to [get_keepers -no_duplicates {soc_inst|subsys_msgdma_p*_eth_ch*|*x_dma_fifo_*|*x_dma_fifo_*|cdc_packet_fifo|*}]
set_false_path -from [get_keepers -no_duplicates {sync_iopll_lock_100M|dreg[*]}] -to [get_keepers -no_duplicates {soc_inst|subsys_msgdma_p*_eth_ch*|*x_dma_fifo_*|*x_dma_fifo_*|to_cntr*}]
set_false_path -from [get_keepers -no_duplicates {inst_srd_rst_ctrl|eth_reset_sync[*].eth_user_*x_rstn_sync_100M|dreg[*]}] -to [get_keepers -no_duplicates {soc_inst|subsys_msgdma_p*_eth_ch*|ts_chs_compl*|ts_chs_compl*|ts_ch_resp*}]
set_false_path -from [get_keepers -no_duplicates {inst_srd_rst_ctrl|eth_reset_sync[*].eth_user_*x_rstn_sync_100M|dreg[*]}] -to [get_keepers -no_duplicates {soc_inst|subsys_msgdma_p*_eth_ch*|ts_chs_compl_0|ts_chs_compl_0|*}]
set_false_path -from [get_keepers -no_duplicates {inst_srd_rst_ctrl|o_user_*x_rst_n_100_*d[*]}] -to [get_keepers -no_duplicates {soc_inst|subsys_msgdma_p*_eth_ch*|*x_dma_fifo_*|*x_dma_fifo_*|cdc_packet_fifo|*}]
set_false_path -from [get_keepers -no_duplicates {inst_srd_rst_ctrl|eth_reset_sync[*].eth_user_*x_rstn_sync_100M*|dreg[*]}] -to [get_keepers -no_duplicates {soc_inst|subsys_msgdma_p*_eth_ch*|*x_dma_fifo_*|*x_dma_fifo_*|to_cntr*}]
set_false_path -from [get_keepers -no_duplicates {sync_iopll_lock_100M*|dreg[*]}] -to [get_keepers -no_duplicates {soc_inst|subsys_msgdma_p*_eth_ch*|rx_dma_fifo_*|rx_dma_fifo_*|ts_fifo_rst*}]
set_false_path -from [get_keepers -no_duplicates {inst_srd_rst_ctrl|eth_reset_sync[*].eth_user_*x_rstn_sync_100M*|dreg[*]}] -to [get_keepers -no_duplicates {soc_inst|subsys_msgdma_p*_eth_ch*|rx_dma_fifo_*|rx_dma_fifo_*|ts_fifo_rst*}]


set_false_path -from [get_keepers -no_duplicates {gen_mulit_inst[1].hssi_ss_top|u0|intel_eth_gts_0|sip_inst|CURRENT_STATE[0].tx_lane_current_sync|sync[0].synchronizer_nocut_inst|dreg_R}] -to [get_keepers -no_duplicates {inst_srd_rst_ctrl|eth_reset_sync[1].sync_rst_ack_n_161_0|dreg[1]}]; if { [ info exists ::timequest_is_busy ] } { qui_ui_vwait ::timequest_is_ready }; set_false_path -from [get_keepers -no_duplicates {gen_mulit_inst[1].hssi_ss_top|u0|intel_eth_gts_0|sip_inst|CURRENT_STATE[0].tx_lane_current_sync|sync[0].synchronizer_nocut_inst|dreg_R}] -to [get_keepers -no_duplicates {inst_srd_rst_ctrl|eth_reset_sync[1].sync_rst_ack_n_161_0|dreg[1]}]
set_false_path -from [get_keepers -no_duplicates {gen_mulit_inst[1].hssi_ss_top|u0|intel_eth_gts_0|sip_inst|CURRENT_STATE[0].tx_lane_current_sync|sync[0].synchronizer_nocut_inst|dreg_R}] -to [get_keepers -no_duplicates {inst_srd_rst_ctrl|eth_reset_sync[1].sync_rst_ack_n_161_0|dreg[0]}]; if { [ info exists ::timequest_is_busy ] } { qui_ui_vwait ::timequest_is_ready }; set_false_path -from [get_keepers -no_duplicates {gen_mulit_inst[1].hssi_ss_top|u0|intel_eth_gts_0|sip_inst|CURRENT_STATE[0].tx_lane_current_sync|sync[0].synchronizer_nocut_inst|dreg_R}] -to [get_keepers -no_duplicates {inst_srd_rst_ctrl|eth_reset_sync[1].sync_rst_ack_n_161_0|dreg[0]}]
set_false_path -from [get_keepers -no_duplicates {gen_mulit_inst[1].hssi_ss_top|u0|intel_eth_gts_0|sip_inst|csr_inst|soft_csr|eth_reset_eio_sys_rst}] -to [get_keepers -no_duplicates {inst_srd_rst_ctrl|eth_reset_sync[1].sync_rst_ack_n_161_0|dreg[1]}]; if { [ info exists ::timequest_is_busy ] } { qui_ui_vwait ::timequest_is_ready }; set_false_path -from [get_keepers -no_duplicates {gen_mulit_inst[1].hssi_ss_top|u0|intel_eth_gts_0|sip_inst|csr_inst|soft_csr|eth_reset_eio_sys_rst}] -to [get_keepers -no_duplicates {inst_srd_rst_ctrl|eth_reset_sync[1].sync_rst_ack_n_161_0|dreg[1]}]
set_false_path -from [get_keepers -no_duplicates {gen_mulit_inst[1].hssi_ss_top|u0|intel_eth_gts_0|sip_inst|csr_inst|soft_csr|eth_reset_eio_sys_rst}] -to [get_keepers -no_duplicates {inst_srd_rst_ctrl|eth_reset_sync[1].sync_rst_ack_n_161_0|dreg[0]}]; if { [ info exists ::timequest_is_busy ] } { qui_ui_vwait ::timequest_is_ready }; set_false_path -from [get_keepers -no_duplicates {gen_mulit_inst[1].hssi_ss_top|u0|intel_eth_gts_0|sip_inst|csr_inst|soft_csr|eth_reset_eio_sys_rst}] -to [get_keepers -no_duplicates {inst_srd_rst_ctrl|eth_reset_sync[1].sync_rst_ack_n_161_0|dreg[0]}]
set_false_path -from [get_keepers -no_duplicates {gen_mulit_inst[1].hssi_ss_top|u0|intel_eth_gts_0|sip_inst|CURRENT_STATE[0].rx_lane_current_sync|sync[0].synchronizer_nocut_inst|dreg_R}] -to [get_keepers -no_duplicates {inst_srd_rst_ctrl|eth_reset_sync[1].sync_rst_ack_n_161_0|dreg[1]}]; if { [ info exists ::timequest_is_busy ] } { qui_ui_vwait ::timequest_is_ready }; set_false_path -from [get_keepers -no_duplicates {gen_mulit_inst[1].hssi_ss_top|u0|intel_eth_gts_0|sip_inst|CURRENT_STATE[0].rx_lane_current_sync|sync[0].synchronizer_nocut_inst|dreg_R}] -to [get_keepers -no_duplicates {inst_srd_rst_ctrl|eth_reset_sync[1].sync_rst_ack_n_161_0|dreg[1]}]
set_false_path -from [get_keepers -no_duplicates {gen_mulit_inst[1].hssi_ss_top|u0|intel_eth_gts_0|sip_inst|CURRENT_STATE[0].rx_lane_current_sync|sync[0].synchronizer_nocut_inst|dreg_R}] -to [get_keepers -no_duplicates {inst_srd_rst_ctrl|eth_reset_sync[1].sync_rst_ack_n_161_0|dreg[0]}]; if { [ info exists ::timequest_is_busy ] } { qui_ui_vwait ::timequest_is_ready }; set_false_path -from [get_keepers -no_duplicates {gen_mulit_inst[1].hssi_ss_top|u0|intel_eth_gts_0|sip_inst|CURRENT_STATE[0].rx_lane_current_sync|sync[0].synchronizer_nocut_inst|dreg_R}] -to [get_keepers -no_duplicates {inst_srd_rst_ctrl|eth_reset_sync[1].sync_rst_ack_n_161_0|dreg[0]}]
set_false_path -from [get_keepers -no_duplicates {gen_mulit_inst[1].hssi_ss_top|u0|intel_eth_gts_0|sip_inst|CURRENT_STATE[0].tx_lane_current_sync|sync[0].synchronizer_nocut_inst|dreg_R}] -to [get_keepers -no_duplicates {inst_srd_rst_ctrl|eth_reset_sync[1].sync_tx_rst_ack_n_161_0|dreg[0]}]; if { [ info exists ::timequest_is_busy ] } { qui_ui_vwait ::timequest_is_ready }; set_false_path -from [get_keepers -no_duplicates {gen_mulit_inst[1].hssi_ss_top|u0|intel_eth_gts_0|sip_inst|CURRENT_STATE[0].tx_lane_current_sync|sync[0].synchronizer_nocut_inst|dreg_R}] -to [get_keepers -no_duplicates {inst_srd_rst_ctrl|eth_reset_sync[1].sync_tx_rst_ack_n_161_0|dreg[0]}]
set_false_path -from [get_keepers -no_duplicates {gen_mulit_inst[1].hssi_ss_top|u0|intel_eth_gts_0|sip_inst|CURRENT_STATE[0].tx_lane_current_sync|sync[0].synchronizer_nocut_inst|dreg_R}] -to [get_keepers -no_duplicates {inst_srd_rst_ctrl|eth_reset_sync[1].sync_tx_rst_ack_n_161_0|dreg[1]}]; if { [ info exists ::timequest_is_busy ] } { qui_ui_vwait ::timequest_is_ready }; set_false_path -from [get_keepers -no_duplicates {gen_mulit_inst[1].hssi_ss_top|u0|intel_eth_gts_0|sip_inst|CURRENT_STATE[0].tx_lane_current_sync|sync[0].synchronizer_nocut_inst|dreg_R}] -to [get_keepers -no_duplicates {inst_srd_rst_ctrl|eth_reset_sync[1].sync_tx_rst_ack_n_161_0|dreg[1]}]
set_false_path -from [get_keepers -no_duplicates {gen_mulit_inst[1].hssi_ss_top|u0|intel_eth_gts_0|sip_inst|CURRENT_STATE[0].rx_lane_current_sync|sync[1].synchronizer_nocut_inst|dreg_R}] -to [get_keepers -no_duplicates {inst_srd_rst_ctrl|eth_reset_sync[1].sync_rx_rst_ack_n_161_0|dreg[1]}]; if { [ info exists ::timequest_is_busy ] } { qui_ui_vwait ::timequest_is_ready }; set_false_path -from [get_keepers -no_duplicates {gen_mulit_inst[1].hssi_ss_top|u0|intel_eth_gts_0|sip_inst|CURRENT_STATE[0].rx_lane_current_sync|sync[1].synchronizer_nocut_inst|dreg_R}] -to [get_keepers -no_duplicates {inst_srd_rst_ctrl|eth_reset_sync[1].sync_rx_rst_ack_n_161_0|dreg[1]}]
set_false_path -from [get_keepers -no_duplicates {gen_mulit_inst[1].hssi_ss_top|u0|intel_eth_gts_0|sip_inst|CURRENT_STATE[0].rx_lane_current_sync|sync[1].synchronizer_nocut_inst|dreg_R}] -to [get_keepers -no_duplicates {inst_srd_rst_ctrl|eth_reset_sync[1].sync_rx_rst_ack_n_161_0|dreg[0]}]; if { [ info exists ::timequest_is_busy ] } { qui_ui_vwait ::timequest_is_ready }; set_false_path -from [get_keepers -no_duplicates {gen_mulit_inst[1].hssi_ss_top|u0|intel_eth_gts_0|sip_inst|CURRENT_STATE[0].rx_lane_current_sync|sync[1].synchronizer_nocut_inst|dreg_R}] -to [get_keepers -no_duplicates {inst_srd_rst_ctrl|eth_reset_sync[1].sync_rx_rst_ack_n_161_0|dreg[0]}]
set_false_path -from [get_keepers -no_duplicates {gen_mulit_inst[1].hssi_ss_top|u0|intel_eth_gts_0|sip_inst|CURRENT_STATE[0].rx_lane_current_sync|sync[1].synchronizer_nocut_inst|dreg_R}] -to [get_keepers -no_duplicates {inst_srd_rst_ctrl|eth_reset_sync[1].sync_rst_ack_n_161_0|dreg[1]}]; if { [ info exists ::timequest_is_busy ] } { qui_ui_vwait ::timequest_is_ready }; set_false_path -from [get_keepers -no_duplicates {gen_mulit_inst[1].hssi_ss_top|u0|intel_eth_gts_0|sip_inst|CURRENT_STATE[0].rx_lane_current_sync|sync[1].synchronizer_nocut_inst|dreg_R}] -to [get_keepers -no_duplicates {inst_srd_rst_ctrl|eth_reset_sync[1].sync_rst_ack_n_161_0|dreg[1]}]
set_false_path -from [get_keepers -no_duplicates {gen_mulit_inst[1].hssi_ss_top|u0|intel_eth_gts_0|sip_inst|CURRENT_STATE[0].rx_lane_current_sync|sync[1].synchronizer_nocut_inst|dreg_R}] -to [get_keepers -no_duplicates {inst_srd_rst_ctrl|eth_reset_sync[1].sync_rst_ack_n_161_0|dreg[0]}]; if { [ info exists ::timequest_is_busy ] } { qui_ui_vwait ::timequest_is_ready }; set_false_path -from [get_keepers -no_duplicates {gen_mulit_inst[1].hssi_ss_top|u0|intel_eth_gts_0|sip_inst|CURRENT_STATE[0].rx_lane_current_sync|sync[1].synchronizer_nocut_inst|dreg_R}] -to [get_keepers -no_duplicates {inst_srd_rst_ctrl|eth_reset_sync[1].sync_rst_ack_n_161_0|dreg[0]}]
set_false_path -from [get_keepers -no_duplicates {sync_i_rst_n_125_1|dreg[1]}] -to [get_keepers -no_duplicates {inst_srd_rst_ctrl|eth_reset_sync[1].sync_rst_ack_n_161_0|dreg[1]}]; if { [ info exists ::timequest_is_busy ] } { qui_ui_vwait ::timequest_is_ready }; set_false_path -from [get_keepers -no_duplicates {sync_i_rst_n_125_1|dreg[1]}] -to [get_keepers -no_duplicates {inst_srd_rst_ctrl|eth_reset_sync[1].sync_rst_ack_n_161_0|dreg[1]}]
set_false_path -from [get_keepers -no_duplicates {sync_i_rst_n_125_1|dreg[1]}] -to [get_keepers -no_duplicates {inst_srd_rst_ctrl|eth_reset_sync[1].sync_rst_ack_n_161_0|dreg[0]}]; if { [ info exists ::timequest_is_busy ] } { qui_ui_vwait ::timequest_is_ready }; set_false_path -from [get_keepers -no_duplicates {sync_i_rst_n_125_1|dreg[1]}] -to [get_keepers -no_duplicates {inst_srd_rst_ctrl|eth_reset_sync[1].sync_rst_ack_n_161_0|dreg[0]}]
set_false_path -from [get_keepers -no_duplicates {gen_mulit_inst[1].hssi_ss_top|u0|intel_eth_gts_0|sip_inst|CURRENT_STATE[0].tx_lane_current_sync|sync[1].synchronizer_nocut_inst|dreg_R}] -to [get_keepers -no_duplicates {inst_srd_rst_ctrl|eth_reset_sync[1].sync_tx_rst_ack_n_161_0|dreg[0]}]; if { [ info exists ::timequest_is_busy ] } { qui_ui_vwait ::timequest_is_ready }; set_false_path -from [get_keepers -no_duplicates {gen_mulit_inst[1].hssi_ss_top|u0|intel_eth_gts_0|sip_inst|CURRENT_STATE[0].tx_lane_current_sync|sync[1].synchronizer_nocut_inst|dreg_R}] -to [get_keepers -no_duplicates {inst_srd_rst_ctrl|eth_reset_sync[1].sync_tx_rst_ack_n_161_0|dreg[0]}]
set_false_path -from [get_keepers -no_duplicates {gen_mulit_inst[1].hssi_ss_top|u0|intel_eth_gts_0|sip_inst|CURRENT_STATE[0].tx_lane_current_sync|sync[1].synchronizer_nocut_inst|dreg_R}] -to [get_keepers -no_duplicates {inst_srd_rst_ctrl|eth_reset_sync[1].sync_tx_rst_ack_n_161_0|dreg[1]}]; if { [ info exists ::timequest_is_busy ] } { qui_ui_vwait ::timequest_is_ready }; set_false_path -from [get_keepers -no_duplicates {gen_mulit_inst[1].hssi_ss_top|u0|intel_eth_gts_0|sip_inst|CURRENT_STATE[0].tx_lane_current_sync|sync[1].synchronizer_nocut_inst|dreg_R}] -to [get_keepers -no_duplicates {inst_srd_rst_ctrl|eth_reset_sync[1].sync_tx_rst_ack_n_161_0|dreg[1]}]
set_false_path -from [get_keepers -no_duplicates {gen_mulit_inst[1].hssi_ss_top|u0|intel_eth_gts_0|sip_inst|CURRENT_STATE[0].tx_lane_current_sync|sync[1].synchronizer_nocut_inst|dreg_R}] -to [get_keepers -no_duplicates {inst_srd_rst_ctrl|eth_reset_sync[1].sync_rst_ack_n_161_0|dreg[1]}]; if { [ info exists ::timequest_is_busy ] } { qui_ui_vwait ::timequest_is_ready }; set_false_path -from [get_keepers -no_duplicates {gen_mulit_inst[1].hssi_ss_top|u0|intel_eth_gts_0|sip_inst|CURRENT_STATE[0].tx_lane_current_sync|sync[1].synchronizer_nocut_inst|dreg_R}] -to [get_keepers -no_duplicates {inst_srd_rst_ctrl|eth_reset_sync[1].sync_rst_ack_n_161_0|dreg[1]}]
set_false_path -from [get_keepers -no_duplicates {gen_mulit_inst[1].hssi_ss_top|u0|intel_eth_gts_0|sip_inst|CURRENT_STATE[0].tx_lane_current_sync|sync[1].synchronizer_nocut_inst|dreg_R}] -to [get_keepers -no_duplicates {inst_srd_rst_ctrl|eth_reset_sync[1].sync_rst_ack_n_161_0|dreg[0]}]; if { [ info exists ::timequest_is_busy ] } { qui_ui_vwait ::timequest_is_ready }; set_false_path -from [get_keepers -no_duplicates {gen_mulit_inst[1].hssi_ss_top|u0|intel_eth_gts_0|sip_inst|CURRENT_STATE[0].tx_lane_current_sync|sync[1].synchronizer_nocut_inst|dreg_R}] -to [get_keepers -no_duplicates {inst_srd_rst_ctrl|eth_reset_sync[1].sync_rst_ack_n_161_0|dreg[0]}]
set_false_path -from [get_keepers -no_duplicates {gen_mulit_inst[1].hssi_ss_top|u0|intel_eth_gts_0|sip_inst|CURRENT_STATE[0].rx_lane_current_sync|sync[0].synchronizer_nocut_inst|dreg_R}] -to [get_keepers -no_duplicates {inst_srd_rst_ctrl|eth_reset_sync[1].sync_rx_rst_ack_n_161_0|dreg[1]}]; if { [ info exists ::timequest_is_busy ] } { qui_ui_vwait ::timequest_is_ready }; set_false_path -from [get_keepers -no_duplicates {gen_mulit_inst[1].hssi_ss_top|u0|intel_eth_gts_0|sip_inst|CURRENT_STATE[0].rx_lane_current_sync|sync[0].synchronizer_nocut_inst|dreg_R}] -to [get_keepers -no_duplicates {inst_srd_rst_ctrl|eth_reset_sync[1].sync_rx_rst_ack_n_161_0|dreg[1]}]
set_false_path -from [get_keepers -no_duplicates {gen_mulit_inst[1].hssi_ss_top|u0|intel_eth_gts_0|sip_inst|CURRENT_STATE[0].rx_lane_current_sync|sync[0].synchronizer_nocut_inst|dreg_R}] -to [get_keepers -no_duplicates {inst_srd_rst_ctrl|eth_reset_sync[1].sync_rx_rst_ack_n_161_0|dreg[0]}]; if { [ info exists ::timequest_is_busy ] } { qui_ui_vwait ::timequest_is_ready }; set_false_path -from [get_keepers -no_duplicates {gen_mulit_inst[1].hssi_ss_top|u0|intel_eth_gts_0|sip_inst|CURRENT_STATE[0].rx_lane_current_sync|sync[0].synchronizer_nocut_inst|dreg_R}] -to [get_keepers -no_duplicates {inst_srd_rst_ctrl|eth_reset_sync[1].sync_rx_rst_ack_n_161_0|dreg[0]}]

set_false_path -from [get_keepers -no_duplicates {gen_mulit_inst[0].hssi_ss_top|u0|intel_eth_gts_0|sip_inst|CURRENT_STATE[0].tx_lane_current_sync|sync[1].synchronizer_nocut_inst|dreg_R}] -to [get_keepers -no_duplicates {inst_srd_rst_ctrl|eth_reset_sync[0].sync_tx_rst_ack_n_161_0|dreg[1]}]; if { [ info exists ::timequest_is_busy ] } { qui_ui_vwait ::timequest_is_ready }; set_false_path -from [get_keepers -no_duplicates {gen_mulit_inst[0].hssi_ss_top|u0|intel_eth_gts_0|sip_inst|CURRENT_STATE[0].tx_lane_current_sync|sync[1].synchronizer_nocut_inst|dreg_R}] -to [get_keepers -no_duplicates {inst_srd_rst_ctrl|eth_reset_sync[0].sync_tx_rst_ack_n_161_0|dreg[1]}]
set_false_path -from [get_keepers -no_duplicates {gen_mulit_inst[0].hssi_ss_top|u0|intel_eth_gts_0|sip_inst|CURRENT_STATE[0].tx_lane_current_sync|sync[1].synchronizer_nocut_inst|dreg_R}] -to [get_keepers -no_duplicates {inst_srd_rst_ctrl|eth_reset_sync[0].sync_tx_rst_ack_n_161_0|dreg[0]}]; if { [ info exists ::timequest_is_busy ] } { qui_ui_vwait ::timequest_is_ready }; set_false_path -from [get_keepers -no_duplicates {gen_mulit_inst[0].hssi_ss_top|u0|intel_eth_gts_0|sip_inst|CURRENT_STATE[0].tx_lane_current_sync|sync[1].synchronizer_nocut_inst|dreg_R}] -to [get_keepers -no_duplicates {inst_srd_rst_ctrl|eth_reset_sync[0].sync_tx_rst_ack_n_161_0|dreg[0]}]
set_false_path -from [get_keepers -no_duplicates {gen_mulit_inst[0].hssi_ss_top|u0|intel_eth_gts_0|sip_inst|CURRENT_STATE[0].tx_lane_current_sync|sync[0].synchronizer_nocut_inst|dreg_R}] -to [get_keepers -no_duplicates {inst_srd_rst_ctrl|eth_reset_sync[0].sync_tx_rst_ack_n_161_0|dreg[1]}]; if { [ info exists ::timequest_is_busy ] } { qui_ui_vwait ::timequest_is_ready }; set_false_path -from [get_keepers -no_duplicates {gen_mulit_inst[0].hssi_ss_top|u0|intel_eth_gts_0|sip_inst|CURRENT_STATE[0].tx_lane_current_sync|sync[0].synchronizer_nocut_inst|dreg_R}] -to [get_keepers -no_duplicates {inst_srd_rst_ctrl|eth_reset_sync[0].sync_tx_rst_ack_n_161_0|dreg[1]}]
set_false_path -from [get_keepers -no_duplicates {gen_mulit_inst[0].hssi_ss_top|u0|intel_eth_gts_0|sip_inst|CURRENT_STATE[0].tx_lane_current_sync|sync[0].synchronizer_nocut_inst|dreg_R}] -to [get_keepers -no_duplicates {inst_srd_rst_ctrl|eth_reset_sync[0].sync_tx_rst_ack_n_161_0|dreg[0]}]; if { [ info exists ::timequest_is_busy ] } { qui_ui_vwait ::timequest_is_ready }; set_false_path -from [get_keepers -no_duplicates {gen_mulit_inst[0].hssi_ss_top|u0|intel_eth_gts_0|sip_inst|CURRENT_STATE[0].tx_lane_current_sync|sync[0].synchronizer_nocut_inst|dreg_R}] -to [get_keepers -no_duplicates {inst_srd_rst_ctrl|eth_reset_sync[0].sync_tx_rst_ack_n_161_0|dreg[0]}]
set_false_path -from [get_keepers -no_duplicates {gen_mulit_inst[0].hssi_ss_top|u0|intel_eth_gts_0|sip_inst|CURRENT_STATE[0].tx_lane_current_sync|sync[0].synchronizer_nocut_inst|dreg_R}] -to [get_keepers -no_duplicates {inst_srd_rst_ctrl|eth_reset_sync[0].sync_rst_ack_n_161_0|dreg[1]}]; if { [ info exists ::timequest_is_busy ] } { qui_ui_vwait ::timequest_is_ready }; set_false_path -from [get_keepers -no_duplicates {gen_mulit_inst[0].hssi_ss_top|u0|intel_eth_gts_0|sip_inst|CURRENT_STATE[0].tx_lane_current_sync|sync[0].synchronizer_nocut_inst|dreg_R}] -to [get_keepers -no_duplicates {inst_srd_rst_ctrl|eth_reset_sync[0].sync_rst_ack_n_161_0|dreg[1]}]
set_false_path -from [get_keepers -no_duplicates {gen_mulit_inst[0].hssi_ss_top|u0|intel_eth_gts_0|sip_inst|CURRENT_STATE[0].tx_lane_current_sync|sync[0].synchronizer_nocut_inst|dreg_R}] -to [get_keepers -no_duplicates {inst_srd_rst_ctrl|eth_reset_sync[0].sync_rst_ack_n_161_0|dreg[0]}]; if { [ info exists ::timequest_is_busy ] } { qui_ui_vwait ::timequest_is_ready }; set_false_path -from [get_keepers -no_duplicates {gen_mulit_inst[0].hssi_ss_top|u0|intel_eth_gts_0|sip_inst|CURRENT_STATE[0].tx_lane_current_sync|sync[0].synchronizer_nocut_inst|dreg_R}] -to [get_keepers -no_duplicates {inst_srd_rst_ctrl|eth_reset_sync[0].sync_rst_ack_n_161_0|dreg[0]}]
set_false_path -from [get_keepers -no_duplicates {gen_mulit_inst[0].hssi_ss_top|u0|intel_eth_gts_0|sip_inst|CURRENT_STATE[0].tx_lane_current_sync|sync[1].synchronizer_nocut_inst|dreg_R}] -to [get_keepers -no_duplicates {inst_srd_rst_ctrl|eth_reset_sync[0].sync_rst_ack_n_161_0|dreg[1]}]; if { [ info exists ::timequest_is_busy ] } { qui_ui_vwait ::timequest_is_ready }; set_false_path -from [get_keepers -no_duplicates {gen_mulit_inst[0].hssi_ss_top|u0|intel_eth_gts_0|sip_inst|CURRENT_STATE[0].tx_lane_current_sync|sync[1].synchronizer_nocut_inst|dreg_R}] -to [get_keepers -no_duplicates {inst_srd_rst_ctrl|eth_reset_sync[0].sync_rst_ack_n_161_0|dreg[1]}]
set_false_path -from [get_keepers -no_duplicates {gen_mulit_inst[0].hssi_ss_top|u0|intel_eth_gts_0|sip_inst|CURRENT_STATE[0].tx_lane_current_sync|sync[1].synchronizer_nocut_inst|dreg_R}] -to [get_keepers -no_duplicates {inst_srd_rst_ctrl|eth_reset_sync[0].sync_rst_ack_n_161_0|dreg[0]}]; if { [ info exists ::timequest_is_busy ] } { qui_ui_vwait ::timequest_is_ready }; set_false_path -from [get_keepers -no_duplicates {gen_mulit_inst[0].hssi_ss_top|u0|intel_eth_gts_0|sip_inst|CURRENT_STATE[0].tx_lane_current_sync|sync[1].synchronizer_nocut_inst|dreg_R}] -to [get_keepers -no_duplicates {inst_srd_rst_ctrl|eth_reset_sync[0].sync_rst_ack_n_161_0|dreg[0]}]
set_false_path -from [get_keepers -no_duplicates {sync_i_rst_n_125_0|dreg[1]}] -to [get_keepers -no_duplicates {inst_srd_rst_ctrl|eth_reset_sync[0].sync_rst_ack_n_161_0|dreg[1]}]; if { [ info exists ::timequest_is_busy ] } { qui_ui_vwait ::timequest_is_ready }; set_false_path -from [get_keepers -no_duplicates {sync_i_rst_n_125_0|dreg[1]}] -to [get_keepers -no_duplicates {inst_srd_rst_ctrl|eth_reset_sync[0].sync_rst_ack_n_161_0|dreg[1]}]
set_false_path -from [get_keepers -no_duplicates {sync_i_rst_n_125_0|dreg[1]}] -to [get_keepers -no_duplicates {inst_srd_rst_ctrl|eth_reset_sync[0].sync_rst_ack_n_161_0|dreg[0]}]; if { [ info exists ::timequest_is_busy ] } { qui_ui_vwait ::timequest_is_ready }; set_false_path -from [get_keepers -no_duplicates {sync_i_rst_n_125_0|dreg[1]}] -to [get_keepers -no_duplicates {inst_srd_rst_ctrl|eth_reset_sync[0].sync_rst_ack_n_161_0|dreg[0]}]
set_false_path -from [get_keepers -no_duplicates {gen_mulit_inst[0].hssi_ss_top|u0|intel_eth_gts_0|sip_inst|CURRENT_STATE[0].rx_lane_current_sync|sync[0].synchronizer_nocut_inst|dreg_R}] -to [get_keepers -no_duplicates {inst_srd_rst_ctrl|eth_reset_sync[0].sync_rx_rst_ack_n_161_0|dreg[0]}]; if { [ info exists ::timequest_is_busy ] } { qui_ui_vwait ::timequest_is_ready }; set_false_path -from [get_keepers -no_duplicates {gen_mulit_inst[0].hssi_ss_top|u0|intel_eth_gts_0|sip_inst|CURRENT_STATE[0].rx_lane_current_sync|sync[0].synchronizer_nocut_inst|dreg_R}] -to [get_keepers -no_duplicates {inst_srd_rst_ctrl|eth_reset_sync[0].sync_rx_rst_ack_n_161_0|dreg[0]}]
set_false_path -from [get_keepers -no_duplicates {gen_mulit_inst[0].hssi_ss_top|u0|intel_eth_gts_0|sip_inst|CURRENT_STATE[0].rx_lane_current_sync|sync[0].synchronizer_nocut_inst|dreg_R}] -to [get_keepers -no_duplicates {inst_srd_rst_ctrl|eth_reset_sync[0].sync_rx_rst_ack_n_161_0|dreg[1]}]; if { [ info exists ::timequest_is_busy ] } { qui_ui_vwait ::timequest_is_ready }; set_false_path -from [get_keepers -no_duplicates {gen_mulit_inst[0].hssi_ss_top|u0|intel_eth_gts_0|sip_inst|CURRENT_STATE[0].rx_lane_current_sync|sync[0].synchronizer_nocut_inst|dreg_R}] -to [get_keepers -no_duplicates {inst_srd_rst_ctrl|eth_reset_sync[0].sync_rx_rst_ack_n_161_0|dreg[1]}]
set_false_path -from [get_keepers -no_duplicates {gen_mulit_inst[0].hssi_ss_top|u0|intel_eth_gts_0|sip_inst|CURRENT_STATE[0].rx_lane_current_sync|sync[1].synchronizer_nocut_inst|dreg_R}] -to [get_keepers -no_duplicates {inst_srd_rst_ctrl|eth_reset_sync[0].sync_rx_rst_ack_n_161_0|dreg[0]}]; if { [ info exists ::timequest_is_busy ] } { qui_ui_vwait ::timequest_is_ready }; set_false_path -from [get_keepers -no_duplicates {gen_mulit_inst[0].hssi_ss_top|u0|intel_eth_gts_0|sip_inst|CURRENT_STATE[0].rx_lane_current_sync|sync[1].synchronizer_nocut_inst|dreg_R}] -to [get_keepers -no_duplicates {inst_srd_rst_ctrl|eth_reset_sync[0].sync_rx_rst_ack_n_161_0|dreg[0]}]
set_false_path -from [get_keepers -no_duplicates {gen_mulit_inst[0].hssi_ss_top|u0|intel_eth_gts_0|sip_inst|CURRENT_STATE[0].rx_lane_current_sync|sync[1].synchronizer_nocut_inst|dreg_R}] -to [get_keepers -no_duplicates {inst_srd_rst_ctrl|eth_reset_sync[0].sync_rx_rst_ack_n_161_0|dreg[1]}]; if { [ info exists ::timequest_is_busy ] } { qui_ui_vwait ::timequest_is_ready }; set_false_path -from [get_keepers -no_duplicates {gen_mulit_inst[0].hssi_ss_top|u0|intel_eth_gts_0|sip_inst|CURRENT_STATE[0].rx_lane_current_sync|sync[1].synchronizer_nocut_inst|dreg_R}] -to [get_keepers -no_duplicates {inst_srd_rst_ctrl|eth_reset_sync[0].sync_rx_rst_ack_n_161_0|dreg[1]}]
set_false_path -from [get_keepers -no_duplicates {gen_mulit_inst[0].hssi_ss_top|u0|intel_eth_gts_0|sip_inst|CURRENT_STATE[0].rx_lane_current_sync|sync[0].synchronizer_nocut_inst|dreg_R}] -to [get_keepers -no_duplicates {inst_srd_rst_ctrl|eth_reset_sync[0].sync_rst_ack_n_161_0|dreg[1]}]; if { [ info exists ::timequest_is_busy ] } { qui_ui_vwait ::timequest_is_ready }; set_false_path -from [get_keepers -no_duplicates {gen_mulit_inst[0].hssi_ss_top|u0|intel_eth_gts_0|sip_inst|CURRENT_STATE[0].rx_lane_current_sync|sync[0].synchronizer_nocut_inst|dreg_R}] -to [get_keepers -no_duplicates {inst_srd_rst_ctrl|eth_reset_sync[0].sync_rst_ack_n_161_0|dreg[1]}]
set_false_path -from [get_keepers -no_duplicates {gen_mulit_inst[0].hssi_ss_top|u0|intel_eth_gts_0|sip_inst|CURRENT_STATE[0].rx_lane_current_sync|sync[0].synchronizer_nocut_inst|dreg_R}] -to [get_keepers -no_duplicates {inst_srd_rst_ctrl|eth_reset_sync[0].sync_rst_ack_n_161_0|dreg[0]}]; if { [ info exists ::timequest_is_busy ] } { qui_ui_vwait ::timequest_is_ready }; set_false_path -from [get_keepers -no_duplicates {gen_mulit_inst[0].hssi_ss_top|u0|intel_eth_gts_0|sip_inst|CURRENT_STATE[0].rx_lane_current_sync|sync[0].synchronizer_nocut_inst|dreg_R}] -to [get_keepers -no_duplicates {inst_srd_rst_ctrl|eth_reset_sync[0].sync_rst_ack_n_161_0|dreg[0]}]
set_false_path -from [get_keepers -no_duplicates {gen_mulit_inst[0].hssi_ss_top|u0|intel_eth_gts_0|sip_inst|csr_inst|soft_csr|eth_reset_eio_sys_rst}] -to [get_keepers -no_duplicates {inst_srd_rst_ctrl|eth_reset_sync[0].sync_rst_ack_n_161_0|dreg[1]}]; if { [ info exists ::timequest_is_busy ] } { qui_ui_vwait ::timequest_is_ready }; set_false_path -from [get_keepers -no_duplicates {gen_mulit_inst[0].hssi_ss_top|u0|intel_eth_gts_0|sip_inst|csr_inst|soft_csr|eth_reset_eio_sys_rst}] -to [get_keepers -no_duplicates {inst_srd_rst_ctrl|eth_reset_sync[0].sync_rst_ack_n_161_0|dreg[1]}]
set_false_path -from [get_keepers -no_duplicates {gen_mulit_inst[0].hssi_ss_top|u0|intel_eth_gts_0|sip_inst|csr_inst|soft_csr|eth_reset_eio_sys_rst}] -to [get_keepers -no_duplicates {inst_srd_rst_ctrl|eth_reset_sync[0].sync_rst_ack_n_161_0|dreg[0]}]; if { [ info exists ::timequest_is_busy ] } { qui_ui_vwait ::timequest_is_ready }; set_false_path -from [get_keepers -no_duplicates {gen_mulit_inst[0].hssi_ss_top|u0|intel_eth_gts_0|sip_inst|csr_inst|soft_csr|eth_reset_eio_sys_rst}] -to [get_keepers -no_duplicates {inst_srd_rst_ctrl|eth_reset_sync[0].sync_rst_ack_n_161_0|dreg[0]}]
set_false_path -from [get_keepers -no_duplicates {gen_mulit_inst[0].hssi_ss_top|u0|intel_eth_gts_0|sip_inst|CURRENT_STATE[0].rx_lane_current_sync|sync[1].synchronizer_nocut_inst|dreg_R}] -to [get_keepers -no_duplicates {inst_srd_rst_ctrl|eth_reset_sync[0].sync_rst_ack_n_161_0|dreg[1]}]; if { [ info exists ::timequest_is_busy ] } { qui_ui_vwait ::timequest_is_ready }; set_false_path -from [get_keepers -no_duplicates {gen_mulit_inst[0].hssi_ss_top|u0|intel_eth_gts_0|sip_inst|CURRENT_STATE[0].rx_lane_current_sync|sync[1].synchronizer_nocut_inst|dreg_R}] -to [get_keepers -no_duplicates {inst_srd_rst_ctrl|eth_reset_sync[0].sync_rst_ack_n_161_0|dreg[1]}]
set_false_path -from [get_keepers -no_duplicates {gen_mulit_inst[0].hssi_ss_top|u0|intel_eth_gts_0|sip_inst|CURRENT_STATE[0].rx_lane_current_sync|sync[1].synchronizer_nocut_inst|dreg_R}] -to [get_keepers -no_duplicates {inst_srd_rst_ctrl|eth_reset_sync[0].sync_rst_ack_n_161_0|dreg[0]}]; if { [ info exists ::timequest_is_busy ] } { qui_ui_vwait ::timequest_is_ready }; set_false_path -from [get_keepers -no_duplicates {gen_mulit_inst[0].hssi_ss_top|u0|intel_eth_gts_0|sip_inst|CURRENT_STATE[0].rx_lane_current_sync|sync[1].synchronizer_nocut_inst|dreg_R}] -to [get_keepers -no_duplicates {inst_srd_rst_ctrl|eth_reset_sync[0].sync_rst_ack_n_161_0|dreg[0]}]

set_false_path -from [get_keepers -no_duplicates {inst_srd_rst_ctrl|eth_reset_sync[1].eth_rst_seq|o_rst_n}] -to [get_keepers -no_duplicates {sync_i_rst_n_125_1|dreg[0]}]; if { [ info exists ::timequest_is_busy ] } { qui_ui_vwait ::timequest_is_ready }; set_false_path -from [get_keepers -no_duplicates {inst_srd_rst_ctrl|eth_reset_sync[1].eth_rst_seq|o_rst_n}] -to [get_keepers -no_duplicates {sync_i_rst_n_125_1|dreg[0]}]
set_false_path -from [get_keepers -no_duplicates {inst_srd_rst_ctrl|eth_reset_sync[1].eth_rst_seq|o_rst_n}] -to [get_keepers -no_duplicates {sync_i_rst_n_125_1|dreg[1]}]; if { [ info exists ::timequest_is_busy ] } { qui_ui_vwait ::timequest_is_ready }; set_false_path -from [get_keepers -no_duplicates {inst_srd_rst_ctrl|eth_reset_sync[1].eth_rst_seq|o_rst_n}] -to [get_keepers -no_duplicates {sync_i_rst_n_125_1|dreg[1]}]
set_false_path -from [get_keepers -no_duplicates {inst_srd_rst_ctrl|eth_reset_sync[0].eth_rst_seq|o_rst_n}] -to [get_keepers -no_duplicates {sync_i_rst_n_125_0|dreg[0]}]; if { [ info exists ::timequest_is_busy ] } { qui_ui_vwait ::timequest_is_ready }; set_false_path -from [get_keepers -no_duplicates {inst_srd_rst_ctrl|eth_reset_sync[0].eth_rst_seq|o_rst_n}] -to [get_keepers -no_duplicates {sync_i_rst_n_125_0|dreg[0]}]
set_false_path -from [get_keepers -no_duplicates {inst_srd_rst_ctrl|eth_reset_sync[0].eth_rst_seq|o_rst_n}] -to [get_keepers -no_duplicates {sync_i_rst_n_125_0|dreg[1]}]; if { [ info exists ::timequest_is_busy ] } { qui_ui_vwait ::timequest_is_ready }; set_false_path -from [get_keepers -no_duplicates {inst_srd_rst_ctrl|eth_reset_sync[0].eth_rst_seq|o_rst_n}] -to [get_keepers -no_duplicates {sync_i_rst_n_125_0|dreg[1]}]



